### ISSUE TITLE
Failing build on zig 0.15.0

### ISSUE THREAD

**Issue by floatdrop** [allyourcodebase/ffmpeg#23]
Since `build.zig.zon` file declares minimal zig version as [0.15.0](https://github.com/allyourcodebase/ffmpeg/blob/main/build.zig.zon#L5) all dependencies should be updated to support this version.

<details>
<summary>Shell output for zig build in ffmpeg repository</summary>

```sh
/Users/floatdrop/.cache/zig/p/libmp3lame-3.100.1-5-67wlF1KvEwDaCOrGGAl9Yb52UG3bcezunnbLcJo2t2HC/build.zig:9:18: error: no field or member function named 'addStaticLibrary' in 'Build'
    const lib = b.addStaticLibrary(.{
                ~^~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
/Users/floatdrop/.cache/zig/p/libmp3lame-3.100.1-5-67wlF1KvEwDaCOrGGAl9Yb52UG3bcezunnbLcJo2t2HC/build.zig:9:18: note: method invocation only supports up to one level of implicit pointer dereferencing
/Users/floatdrop/.cache/zig/p/libmp3lame-3.100.1-5-67wlF1KvEwDaCOrGGAl9Yb52UG3bcezunnbLcJo2t2HC/build.zig:9:18: note: use '.*' to dereference pointer
referenced by:
    runBuild__anon_74278: /opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:2214:33
    dependencyInner__anon_71476: /opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:2195:29
    8 reference(s) hidden; use '-freference-trace=10' to see all references
/Users/floatdrop/.cache/zig/p/libogg-1.3.6-3-ZBKq7fQUAgCz4fszMXyS-erQljD2tL5Z6A0Kh4B1T4qk/build.zig:7:18: error: no field or member function named 'addStaticLibrary' in 'Build'
    const lib = b.addStaticLibrary(.{
                ~^~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
/Users/floatdrop/.cache/zig/p/libogg-1.3.6-3-ZBKq7fQUAgCz4fszMXyS-erQljD2tL5Z6A0Kh4B1T4qk/build.zig:7:18: note: method invocation only supports up to one level of implicit pointer dereferencing
/Users/floatdrop/.cache/zig/p/libogg-1.3.6-3-ZBKq7fQUAgCz4fszMXyS-erQljD2tL5Z6A0Kh4B1T4qk/build.zig:7:18: note: use '.*' to dereference pointer
/Users/floatdrop/.cache/zig/p/libvorbis-1.3.8-4-gL_KI2kPJACPcXW6H_SSrsaRnauuaJGPS9wPqg5ALE8q/build.zig:12:18: error: no field or member function named 'addStaticLibrary' in 'Build'
    const lib = b.addStaticLibrary(.{
                ~^~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
/Users/floatdrop/.cache/zig/p/libvorbis-1.3.8-4-gL_KI2kPJACPcXW6H_SSrsaRnauuaJGPS9wPqg5ALE8q/build.zig:12:18: note: method invocation only supports up to one level of implicit pointer dereferencing
/Users/floatdrop/.cache/zig/p/libvorbis-1.3.8-4-gL_KI2kPJACPcXW6H_SSrsaRnauuaJGPS9wPqg5ALE8q/build.zig:12:18: note: use '.*' to dereference pointer
/Users/floatdrop/.cache/zig/p/nasm-2.16.1-4-J30EdyVnXADate9iz7jWR4Q9tL1jU9S2Lw7PGgfOjP0v/build.zig:11:10: error: no field named 'target' in struct 'Build.ExecutableOptions'
        .target = target,
         ^~~~~~
/opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
/Users/floatdrop/.cache/zig/p/zlib-1.3.1-ZZQ7lVgMAACwO4nUUd8GLhsuQ5JQq_VAhlEiENJTUv6h/build.zig:5:18: error: no field or member function named 'addStaticLibrary' in 'Build'
    const lib = b.addStaticLibrary(.{
                ~^~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
/Users/floatdrop/.cache/zig/p/zlib-1.3.1-ZZQ7lVgMAACwO4nUUd8GLhsuQ5JQq_VAhlEiENJTUv6h/build.zig:5:18: note: method invocation only supports up to one level of implicit pointer dereferencing
/Users/floatdrop/.cache/zig/p/zlib-1.3.1-ZZQ7lVgMAACwO4nUUd8GLhsuQ5JQq_VAhlEiENJTUv6h/build.zig:5:18: note: use '.*' to dereference pointer
build.zig:39:18: error: no field or member function named 'addStaticLibrary' in 'Build'
    const lib = b.addStaticLibrary(.{
                ~^~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
build.zig:39:18: note: method invocation only supports up to one level of implicit pointer dereferencing
build.zig:39:18: note: use '.*' to dereference pointer
```

</details>

Common issue in dependencies is that `addStaticLibrary` was replaced by `addLibrary` and this change must be propagated to dependencies as well.

Here list of prs/issues/releases to be merged/resolved/updated to make `ffmpeg` build again:

- [x] libz (looks ok)
- [ ] mbedtls - https://github.com/allyourcodebase/mbedtls/pull/4
- [ ] openssl - https://github.com/allyourcodebase/openssl/releases/tag/3.3.2
- [ ] libressl - https://github.com/allyourcodebase/libressl/releases/tag/4.0.0%2B3
- [ ] libmp3lame - https://github.com/allyourcodebase/libmp3lame/pull/5
- [ ] libvorbis - https://github.com/andrewrk/libvorbis/pull/1
- [ ] libogg - https://github.com/andrewrk/libogg/pull/1
- [ ] nasm - https://github.com/allyourcodebase/nasm/pull/8

**Comment by francisqureshi** [comment]
It would be great to get these all merged in pretty please!  I am doing some silly footwork at the moment myself which i'd rather not do! 🕺
